C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapgetqvs (getqvsf2pywrap, p, t)
      external getqvs
      real p
      real t
      real getqvsf2pywrap, getqvs
      getqvsf2pywrap = getqvs(p, t)
      end


      subroutine f2pywrapgetqvi (getqvif2pywrap, p, t)
      external getqvi
      real p
      real t
      real getqvif2pywrap, getqvi
      getqvif2pywrap = getqvi(p, t)
      end


      subroutine f2pywrapgetthe (getthef2pywrap, p, t, td, q)
      external getthe
      real p
      real t
      real td
      real q
      real getthef2pywrap, getthe
      getthef2pywrap = getthe(p, t, td, q)
      end

